name: spotify_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.9
  flutter_svg: ^2.0.10+1
  flutter_bloc: ^8.1.6
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.6
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  get_it: ^8.3.0
  dartz: ^0.10.1
  cloud_firestore: ^5.6.5
  just_audio: ^0.9.42

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/vectors/
  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Black.ttf
          weight: 900
        - asset: assets/fonts/Satoshi-Bold.ttf
          weight: 600
        - asset: assets/fonts/Satoshi-Medium.ttf
          weight: 500
        - asset: assets/fonts/Satoshi-Regular.ttf
          weight: 400
        - asset: assets/fonts/Satoshi-Light.ttf
          weight: 300
